name: pull

on:
  pull_request:
    branches-ignore:
      - nightly
  push:
    branches:
      - main
      - release/*
      - landchecks/*
  workflow_dispatch:
  schedule:
    - cron: 29 8 * * *  # about 1:29am PDT

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

jobs:
  linux-focal-rocm5_4_2-py3_8-build:
    name: linux-focal-rocm5.4.2-py3.8
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-focal-rocm5.4.2-py3.8
      docker-image-name: pytorch-linux-focal-rocm-n-py3
      sync-tag: rocm-build
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 3, runner: "linux.rocm.gpu" },
          { config: "default", shard: 2, num_shards: 3, runner: "linux.rocm.gpu" },
          { config: "default", shard: 3, num_shards: 3, runner: "linux.rocm.gpu" },
        ]}

  linux-focal-rocm5_4_2-py3_8-test:
    name: linux-focal-rocm5.4.2-py3.8
    uses: ./.github/workflows/_rocm-test.yml
    needs: linux-focal-rocm5_4_2-py3_8-build
    with:
      build-environment: linux-focal-rocm5.4.2-py3.8
      docker-image: ${{ needs.linux-focal-rocm5_4_2-py3_8-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-focal-rocm5_4_2-py3_8-build.outputs.test-matrix }}
    secrets:
      AWS_OSSCI_METRICS_V2_ACCESS_KEY_ID: ${{ secrets.AWS_OSSCI_METRICS_V2_ACCESS_KEY_ID }}
      AWS_OSSCI_METRICS_V2_SECRET_ACCESS_KEY: ${{ secrets.AWS_OSSCI_METRICS_V2_SECRET_ACCESS_KEY }}
